version: "3"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /run/desktop/mnt/host/z/config/lidarr:/config
      - /run/desktop/mnt/host/f/Discographies:/music
      - /run/desktop/mnt/host/c/Users/paull/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
