version: "3"
services:
  ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /run/desktop/mnt/host/z/config/ubooquity:/config
      - /run/desktop/mnt/host/f/eBook:/books
      - /run/desktop/mnt/host/f/Comics:/comics
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped
