version: "3"
volumes:
  plex:
    external: true
  ubooquity:
    external: true
  sonarr:
    external: true
  jackett:
    external: true
  transmission:
    external: true
  films:
    external: true
  films2:
    external: true
  series:
    external: true
  series2:
    external: true
  animes:
    external: true
  documentaires:
    external: true
  mini:
    external: true
  books:
    external: true
  comics:
    external: true
  music:
    external: true
  down:
    external: true
    
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - plex:/config
      - films:/films
      - series:/series
      - films2:/films2
      - series2:/series2
      - animes:/animes
      - documentaires:/documentaires
      - mini:/mini
      - music:/music
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    
  ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ubooquity:/config
      - books:/books
      - comics:/comics
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - sonarr:/config
      - animes:/animes
      - series:/Series
      - series2:/Series2
      - documentaires:/documentaires
      - mini:/miniseries
    ports:
      - 8989:8989
    restart: unless-stopped
    
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=run options here #optional
    volumes:
      - jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=admin
      - PASS=password
    volumes:
      - transmission:/config
      - down:/downloads
      - down:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
